#!/bin/sh

# PROVIDE: VCLASSICCOIN
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# VCLASSICCOIN_enable (bool): Set to NO by default. Set this variable to YES if you want to enable VCLASSICCOIN service.
# VCLASSICCOIN_config (path): Set to /usr/local/etc/VCLASSICCOIN.conf by default.
# VCLASSICCOIN_user:  The user account VCLASSICCOIN daemon runs as. It uses 'root' user by default.
# VCLASSICCOIN_group: The group account VCLASSICCOIN daemon runs as. It uses 'wheel' group by default.
# VCLASSICCOIN_datadir (str): Default to "/var/db/VCLASSICCOIN". Base data directory.

. /etc/rc.subr

name=VCLASSICCOIN
rcvar=VCLASSICCOIN_enable

: ${VCLASSICCOIN_enable:=NO}
: ${VCLASSICCOIN_config=/usr/local/etc/VCLASSICCOIN.conf}
: ${VCLASSICCOIN_datadir=/var/db/VCLASSICCOIN}
: ${VCLASSICCOIN_user="root"}
: ${VCLASSICCOIN_group="wheel"}

required_files=${VCLASSICCOIN_config}
command=/usr/local/bin/VCLASSICCOINd
VCLASSICCOIN_chdir=${VCLASSICCOIN_datadir}
pidfile="${VCLASSICCOIN_datadir}/VCLASSICCOINd.pid"
stop_cmd=VCLASSICCOIN_stop
command_args="-conf=${VCLASSICCOIN_config} -datadir=${VCLASSICCOIN_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

VCLASSICCOIN_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${VCLASSICCOIN_datadir}
	[ $? -eq 0 ] && chown -R ${VCLASSICCOIN_user}:${VCLASSICCOIN_group} ${VCLASSICCOIN_datadir}
}

VCLASSICCOIN_prestart()
{
	if [ ! -d "${VCLASSICCOIN_datadir}/." ]; then
		VCLASSICCOIN_create_datadir || return 1
	fi
}

VCLASSICCOIN_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

VCLASSICCOIN_stop()
{
    VCLASSICCOIN_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${VCLASSICCOIN_config} -datadir=${VCLASSICCOIN_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
